language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build  
  - npm run prod
  - npm run test:e2e
  - npm run test:unit

  deploy:
  provider: heroku
  api_key: d4a69bab-d8ef-40dd-856c-19512e0927f0
  app: introcept
  skip_cleanup: true
  github_token: 477a3ea381a28d48e2b6838ccac038f89dbb2cb5 
  local_dir: build
  on:
    branch: master