language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run test:e2e
  - npm run test:unit
  - npm run build  

  deploy:
  provider: heroku
  api_key: d4a69bab-d8ef-40dd-856c-19512e0927f0
  app: introcept
  skip_cleanup: true
  github_token: a3b5156e4513cb84041b85d29697f1d822b27d39  
  local_dir: build
  on:
    branch: master